In [ ]:
import pandas
dfs = pandas.read_html("https://rate.bot.com.tw/xrt?Lang=zh-TW")

In [ ]:
type(dfs)

list

In [ ]:
len(dfs)

1

In [ ]:
dfs[0]

                        幣別  ... Unnamed: 16_level_0
                        幣別  ... Unnamed: 16_level_1
0       美金 (USD)  美金 (USD)  ...                 NaN
1       港幣 (HKD)  港幣 (HKD)  ...                 NaN
2       英鎊 (GBP)  英鎊 (GBP)  ...                 NaN
3       澳幣 (AUD)  澳幣 (AUD)  ...                 NaN
4   加拿大幣 (CAD)  加拿大幣 (CAD)  ...                 NaN
5   新加坡幣 (SGD)  新加坡幣 (SGD)  ...                 NaN
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)  ...                 NaN
7       日圓 (JPY)  日圓 (JPY)  ...                 NaN
8     南非幣 (ZAR)  南非幣 (ZAR)  ...                 NaN
9     瑞典幣 (SEK)  瑞典幣 (SEK)  ...                 NaN
10      紐元 (NZD)  紐元 (NZD)  ...                 NaN
11      泰幣 (THB)  泰幣 (THB)  ...                 NaN
12  菲國比索 (PHP)  菲國比索 (PHP)  ...                 NaN
13    印尼幣 (IDR)  印尼幣 (IDR)  ...                 NaN
14      歐元 (EUR)  歐元 (EUR)  ...                 NaN
15      韓元 (KRW)  韓元 (KRW)  ...                 NaN
16    越南盾 (VND)  越南盾 (VND)  ...                 NaN
17    馬來幣 (MYR)  馬來幣 (MYR)  ...                 NaN
18    人民幣 (CNY)  人民幣 (CNY)  ...                 NaN

[19 rows x 17 columns]

In [ ]:
currency = dfs[0]
print(currency)

                        幣別  ... Unnamed: 16_level_0
                        幣別  ... Unnamed: 16_level_1
0       美金 (USD)  美金 (USD)  ...                 NaN
1       港幣 (HKD)  港幣 (HKD)  ...                 NaN
2       英鎊 (GBP)  英鎊 (GBP)  ...                 NaN
3       澳幣 (AUD)  澳幣 (AUD)  ...                 NaN
4   加拿大幣 (CAD)  加拿大幣 (CAD)  ...                 NaN
5   新加坡幣 (SGD)  新加坡幣 (SGD)  ...                 NaN
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)  ...                 NaN
7       日圓 (JPY)  日圓 (JPY)  ...                 NaN
8     南非幣 (ZAR)  南非幣 (ZAR)  ...                 NaN
9     瑞典幣 (SEK)  瑞典幣 (SEK)  ...                 NaN
10      紐元 (NZD)  紐元 (NZD)  ...                 NaN
11      泰幣 (THB)  泰幣 (THB)  ...                 NaN
12  菲國比索 (PHP)  菲國比索 (PHP)  ...                 NaN
13    印尼幣 (IDR)  印尼幣 (IDR)  ...                 NaN
14      歐元 (EUR)  歐元 (EUR)  ...                 NaN
15      韓元 (KRW)  韓元 (KRW)  ...                 NaN
16    越南盾 (VND)  越南盾 (VND)  ...                 NaN
17    馬來幣 (MYR)  馬來幣 (MYR)  ...                 NaN
18    人民幣 (CNY)  人民幣 (CNY)  ...                 NaN

[19 rows x 17 columns]

In [ ]:
type(currency)

pandas.core.frame.DataFrame

In [ ]:
curr=currency.iloc[:,0:5]

In [ ]:
curr

                        幣別                     ...   現金匯率 Unnamed: 4_level_0
                        幣別 Unnamed: 1_level_1  ...   本行賣出               本行買入
0       美金 (USD)  美金 (USD)              29.18  ...  29.53              29.63
1       港幣 (HKD)  港幣 (HKD)               3.66  ...  3.786              3.846
2       英鎊 (GBP)  英鎊 (GBP)              36.05  ...  37.05              37.47
3       澳幣 (AUD)  澳幣 (AUD)              20.16  ...  20.43              20.66
4   加拿大幣 (CAD)  加拿大幣 (CAD)              21.24  ...  21.63              21.85
5   新加坡幣 (SGD)  新加坡幣 (SGD)              20.66  ...  21.15              21.33
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)              30.59  ...  31.25              31.54
7       日圓 (JPY)  日圓 (JPY)             0.2677  ...  0.275              0.279
8     南非幣 (ZAR)  南非幣 (ZAR)                  -  ...  1.711              1.791
9     瑞典幣 (SEK)  瑞典幣 (SEK)               2.82  ...   3.16               3.26
10      紐元 (NZD)  紐元 (NZD)              18.94  ...  19.32              19.52
11      泰幣 (THB)  泰幣 (THB)             0.8176  ...   0.93               0.97
12  菲國比索 (PHP)  菲國比索 (PHP)             0.5244  ...      -                  -
13    印尼幣 (IDR)  印尼幣 (IDR)            0.00173  ...      -                  -
14      歐元 (EUR)  歐元 (EUR)              32.56  ...  33.18              33.58
15      韓元 (KRW)  韓元 (KRW)            0.02288  ...      -                  -
16    越南盾 (VND)  越南盾 (VND)             0.0009  ...      -                  -
17    馬來幣 (MYR)  馬來幣 (MYR)              5.818  ...      -                  -
18    人民幣 (CNY)  人民幣 (CNY)              4.122  ...  4.194              4.244

[19 rows x 5 columns]

In [ ]:
curr.columns = [u'幣別',u'現金匯率-本行買入',u'現金匯率-本行賣出',u'即期匯率-本行買入',u'即期匯率-本行賣出']

In [ ]:
curr[u'幣別']=curr[u'幣別'].str.extract('\((\w+)\)')

In [ ]:
curr

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出
0   USD     29.18     29.85     29.53     29.63
1   HKD      3.66     3.864     3.786     3.846
2   GBP     36.05     38.17     37.05     37.47
3   AUD     20.16     20.94     20.43     20.66
4   CAD     21.24     22.15     21.63     21.85
5   SGD     20.66     21.57     21.15     21.33
6   CHF     30.59     31.79     31.25     31.54
7   JPY    0.2677    0.2805     0.275     0.279
8   ZAR         -         -     1.711     1.791
9   SEK      2.82      3.34      3.16      3.26
10  NZD     18.94     19.79     19.32     19.52
11  THB    0.8176    1.0076      0.93      0.97
12  PHP    0.5244    0.6574         -         -
13  IDR   0.00173   0.00243         -         -
14  EUR     32.56      33.9     33.18     33.58
15  KRW   0.02288   0.02678         -         -
16  VND    0.0009    0.0014         -         -
17  MYR     5.818     7.443         -         -
18  CNY     4.122     4.284     4.194     4.244

In [ ]:
curr.to_excel('currency.xlsx')